# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1043, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtcaesarcipher = QtWidgets.QLabel(self.centralwidget)
        self.txtcaesarcipher.setGeometry(QtCore.QRect(320, 30, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.txtcaesarcipher.setFont(font)
        self.txtcaesarcipher.setObjectName("txtcaesarcipher")
        self.txtplaitext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtplaitext.setGeometry(QtCore.QRect(220, 120, 651, 101))
        self.txtplaitext.setObjectName("txtplaitext")
        self.txtkey = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtkey.setGeometry(QtCore.QRect(220, 250, 641, 21))
        self.txtkey.setObjectName("txtkey")
        self.txtciphertext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtciphertext.setGeometry(QtCore.QRect(220, 360, 661, 91))
        self.txtciphertext.setObjectName("txtciphertext")
        self.bntencrypt = QtWidgets.QPushButton(self.centralwidget)
        self.bntencrypt.setGeometry(QtCore.QRect(220, 510, 91, 41))
        self.bntencrypt.setObjectName("bntencrypt")
        self.bntdecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.bntdecrypt.setGeometry(QtCore.QRect(670, 520, 91, 41))
        self.bntdecrypt.setObjectName("bntdecrypt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 160, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 260, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 400, 71, 31))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1043, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txtcaesarcipher.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.bntencrypt.setText(_translate("MainWindow", "Encrypt"))
        self.bntdecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.label.setText(_translate("MainWindow", "Plain Text:"))
        self.label_2.setText(_translate("MainWindow", "key"))
        self.label_3.setText(_translate("MainWindow", "CipherText:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
